name: CI

on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode13.4.1.app
      
    - name: Build and test
      run: xcodebuild clean build test -workspace Sample_CoreLocation.xcodeproj -scheme "Sample_CoreLocation" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
