name: CI

on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Build and test
      run: xcodebuild clean build test -xcodeproj Sample_CoreLocation.xcodeproj -scheme "Sample_CoreLocation" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11"
